export enum CategoryEnum {
  Animals = 27,
  Art = 25,
  Celebrities = 26,
  Entertainment_Board_Games = 16,
  Entertainment_Books= 10 ,
  Entertainment_Comics = 29,
  Entertainment_Cartoon_Animations = 32,
  Entertainment_Film = 11,
  Entertainment_Japanese_Anime_Manga = 31,
  Entertainment_Music = 12,
  Entertainment_Musicals_Theatres = 13,
  Entertainment_Television = 14,
  Entertainment_Video_Games = 15,
  General_Knowledge = 9,
  Geography = 22,
  History = 23,
  Mythology = 20,
  Politics = 24,
  Science_Computers = 18,
  Science_Gadgets = 30,
  Sciences_Mathematics = 19,
  Science_Nature  = 17,
  Sports = 21,
  Vehicles = 28,
}

export const FileType2LabelMapping: Record<CategoryEnum, string> = {
  [CategoryEnum.Animals]: "Animals",
  [CategoryEnum.Art]: "Art",
  [CategoryEnum.Celebrities]: "Celebrities",
  [CategoryEnum.Entertainment_Board_Games]: "Entertainment: Board Games",
  [CategoryEnum.Entertainment_Books]: "Entertainment: Books",
  [CategoryEnum.Entertainment_Comics]: "Entertainment: Comics",
  [CategoryEnum.Entertainment_Cartoon_Animations]: "Entertainment: Cartoon & Animations",
  [CategoryEnum.Entertainment_Film]: "Entertainment: Film",
  [CategoryEnum.Entertainment_Japanese_Anime_Manga]: "Entertainment: Japanese Anime & Manga",
  [CategoryEnum.Entertainment_Music]: "Entertainment: Music",
  [CategoryEnum.Entertainment_Musicals_Theatres]: "Entertainment: Musicals & Theatres",
  [CategoryEnum.Entertainment_Television]: "Entertainment: Television",
  [CategoryEnum.Entertainment_Video_Games]: "Entertainment: Video Games",
  [CategoryEnum.General_Knowledge]: "General Knowledge",
  [CategoryEnum.Geography]: "Geography",
  [CategoryEnum.History]: "History",
  [CategoryEnum.Mythology]: "Mythology",
  [CategoryEnum.Politics]: "Politics",
  [CategoryEnum.Science_Computers]: "Science: Computers",
  [CategoryEnum.Science_Gadgets]: "Science: Gadgets",
  [CategoryEnum.Sciences_Mathematics]: "Science: Mathematics",
  [CategoryEnum.Science_Nature]: "Science: Nature",
  [CategoryEnum.Sports]: "Sports",
  [CategoryEnum.Vehicles]: "Vehicles"
}
