export enum CategoryEnum {
  SELECT_CATEGORY = 0,
  ANIMALS = 27,
  ART = 25,
  CELEBRITIES = 26,
  ENTERTAINMENT_BOARD_GAMES = 16,
  ENTERTAINMENT_BOOKS= 10 ,
  ENTERTAINMENT_COMICS = 29,
  ENTERTAINMENT_CARTOON_ANIMATIONS = 32,
  ENTERTAINMENT_FILM = 11,
  ENTERTAINMENT_JAPANESE_ANIME_MANGA = 31,
  ENTERTAINMENT_MUSIC = 12,
  ENTERTAINMENT_MUSICALS_THEATRES = 13,
  ENTERTAINMENT_TELEVISION = 14,
  ENTERTAINMENT_VIDEO_GAMES = 15,
  GENERAL_KNOWLEDGE = 9,
  GEOGRAPHY = 22,
  HISTORY = 23,
  MYTHOLOGY = 20,
  POLITICS = 24,
  SCIENCE_COMPUTERS = 18,
  SCIENCE_GADGETS = 30,
  SCIENCES_MATHEMATICS = 19,
  SCIENCE_NATURE  = 17,
  SPORTS = 21,
  VEHICLES = 28,
}

export const FileType2LabelMapping: Record<CategoryEnum, string> = {
  [CategoryEnum.SELECT_CATEGORY]: 'Select Category',
  [CategoryEnum.ANIMALS]: "Animals",
  [CategoryEnum.ART]: "Art",
  [CategoryEnum.CELEBRITIES]: "Celebrities",
  [CategoryEnum.ENTERTAINMENT_BOARD_GAMES]: "Entertainment: Board Games",
  [CategoryEnum.ENTERTAINMENT_BOOKS]: "Entertainment: Books",
  [CategoryEnum.ENTERTAINMENT_COMICS]: "Entertainment: Comics",
  [CategoryEnum.ENTERTAINMENT_CARTOON_ANIMATIONS]: "Entertainment: Cartoon & Animations",
  [CategoryEnum.ENTERTAINMENT_FILM]: "Entertainment: Film",
  [CategoryEnum.ENTERTAINMENT_JAPANESE_ANIME_MANGA]: "Entertainment: Japanese Anime & Manga",
  [CategoryEnum.ENTERTAINMENT_MUSIC]: "Entertainment: Music",
  [CategoryEnum.ENTERTAINMENT_MUSICALS_THEATRES]: "Entertainment: Musicals & Theatres",
  [CategoryEnum.ENTERTAINMENT_TELEVISION]: "Entertainment: Television",
  [CategoryEnum.ENTERTAINMENT_VIDEO_GAMES]: "Entertainment: Video Games",
  [CategoryEnum.GENERAL_KNOWLEDGE]: "General Knowledge",
  [CategoryEnum.GEOGRAPHY]: "Geography",
  [CategoryEnum.HISTORY]: "History",
  [CategoryEnum.MYTHOLOGY]: "Mythology",
  [CategoryEnum.POLITICS]: "Politics",
  [CategoryEnum.SCIENCE_COMPUTERS]: "Science: Computers",
  [CategoryEnum.SCIENCE_GADGETS]: "Science: Gadgets",
  [CategoryEnum.SCIENCES_MATHEMATICS]: "Science: Mathematics",
  [CategoryEnum.SCIENCE_NATURE]: "Science: Nature",
  [CategoryEnum.SPORTS]: "Sports",
  [CategoryEnum.VEHICLES]: "Vehicles"
}
